apiVersion: v1
kind: Namespace
metadata:
  name: gitops-test-area

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gitops-nginx
  namespace: gitops-test-area

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gitops-nginx

  template:
    metadata:
      labels:
        app: gitops-nginx

    spec:
      containers:
        - name: nginx
          image: nginx:1.27.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-gitops-nginx-service
  namespace: gitops-test-area

spec:
  selector:
    app: gitops-nginx

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
